### ISSUE TITLE
Unslick setting not working

### ISSUE THREAD

**Issue by yenly** [akiran/react-slick#1081]
I upgraded to v.19 and this setting is breaking my layouts. Unslick setting failed to change `.slick-slider` to  `.unslick` on container wrapping `.slick-list`. Is this left out on purpose? Weird thing is that this setting works on smaller breakpoint values. I have both on the same page and one works and the larger doesn't.
Example code: https://codesandbox.io/s/n4yvkqn46j

**Comment by laveesingh** [comment]
Thanks for pointing it out.
Commit: af6d2da7aae298e8256a0cc8a05abf14d8e4d431 should fix this, this change will release soon.

**Comment by yenly** [comment]
I'm still seeing this bug in v0.20.0. as seen here:
https://codesandbox.io/s/vmxv13rz43

**Comment by laveesingh** [comment]
@yenly I'm not sure that's still the case. I copied the snippet from your demo to run with my custom CSS, and it's working fine. Looks like you need to be careful with your CSS.
![responsive](https://user-images.githubusercontent.com/8917978/37077485-38fa9642-2201-11e8-9daa-0e95ad2ffd5e.gif)

**Comment by yenly** [comment]
In previous versions, when we choose to unslick, it changes CSS classes .slick-slider to .unslick. That lets us use our own custom CSS. Currently in 0.20, it still shows as <div class="slick-initialized slick-slider"> which is forcing unneeded styling and limits flexible use. 
<img width="1451" alt="screen shot 2018-03-15 at 2 43 08 pm" src="https://user-images.githubusercontent.com/6759658/37492811-f4af989c-285f-11e8-85b2-243faa88c6a1.png">

**Comment by laveesingh** [comment]
Readded the 'unslicked' class. Thanks!
https://github.com/akiran/react-slick/pull/1087/commits/231e91d7eb4f89705b9da434ef6f1a0bc9184cb4

**Comment by yenly** [comment]
I apologize for having to return to this again. Your latest fix adds .unslicked but it doesn't removed .slick-initialized .slick-slider. Having these classes requires having extra CSS to override those two classes. **Previous versions of react-slick, replaces .slick-initialized .slick-slider with .unslicked when we use setting: 'unslick'.**

**Comment by laveesingh** [comment]
[slick](https://github.com/kenwheeler/slick) retains similar behaviour, so that's what we're going to retain.
We currently have 'unslicked' class so that you can apply different styling in case of unslick mode, but you shouldn't even rely upon that because that's more likely to be removed in a stable release.

Just know that `unslick` mode will be enabled if `unslick` settings are passed or `slickesToShow >= slideCount`. You can keep track of both the conditions and pass the `className` prop accordingly so that you can handle unslicked styles as you like.

**Comment by yenly** [comment]
I appreciate all the work you're doing, @laveesingh. Ken Wheeler's slick library does not have a similar behavior. I download his library examples and set the first one to unslick to explore the HTML. As shown in the screen capture, the original slick library removes .slick-initialized .slick-slider. as well as all slider CSS classes to prevent unwanted cascaded styles applied to its child elements. I hope you would reconsider.

![screen shot 2018-03-20 at 3 23 15 pm](https://user-images.githubusercontent.com/6759658/37686110-4697fd10-2c53-11e8-8bf4-07ddc1cd6040.png)

**Comment by laveesingh** [comment]
@yenly you are right. I missed the point that slick has two kinds of unslick behaviour. One if explicitly unslicked and second if slidesToShow > slideCount. Thank you for notifying the error.
I dug a bit deeper and commit a44da263d56e02181997951ac008f84eb81e4e30 does what we're looking for.

**Comment by laveesingh** [comment]
This has been impelemented and will be released soon.

**Comment by havantuan** [comment]
how to disable height in class slick-track? Can you hep me?

**Comment by lauraseidler** [comment]
@laveesingh this seems broken again? I don't see a way to recognise an unslicked slider in the current 0.23.2 version..
