### ISSUE TITLE
Lazy load an offset amount of images

### ISSUE THREAD

**Issue by gkilian** [akiran/react-slick#390]
### Proposal:

Allow for an offset of images to be lazy loaded, rather than just the one.
### Problem:

Currently when swiping through a set of images with `lazyLoad` set to `true`,  the next image in the queue doesn't start loading until you've committed to the swipe. This causes a second (like in the react-slick examples) or more (when using large images) of no image loaded in the slide.
### Solution:

By implementing something along the lines of `lazyLoadOffset`, we can add a ranges of images to be loaded from the start. Then progressively load the others as the user continues to swipe.

I'm not sure if the community is interested in this functionality. My team has implemented this in our fork of react-slick and are willing to help port over the code if wanted.

**Comment by akiran** [comment]
This issue is fixed in latest release

**Comment by gkilian** [comment]
@akiran - Can we re-open this? I'm not sure that it's actually resolved. 

Although it does seem to quickly load the next image, it's still not loading the image in advance. Thus, while you are in swiping the next images is not there.

This works fine in the Demo example because the next image is off screen, but it doesn't work so well when images are back to back.

**Comment by janicklas-ralph** [comment]
Any update on this? Would be really nice to have this.

**Comment by i8ramin** [comment]
Hello. Wondering if there was any progress made on this issue

**Comment by emilbruckner** [comment]
This is essential

**Comment by markoshust** [comment]
@gkilian do you have the code for this? appears this wasn't pulled into this repo yet. i could really use this functionality. cheers -m

**Comment by gkilian** [comment]
@markoshust - I do in our Condenast fork. I'll submit a PR and tag the people in the PR for review

**Comment by SBRK** [comment]
Would love this as well

**Comment by gkilian** [comment]
@akiran - Are implementation on Conde requires the use of a added prop `lazyLoadOffset`. A secondary PR of mine was closed due to the fact that it supported a non `slick-js` prop. 

Would this be the case for this issue as well? I would hate to write a PR if the end result is the same.

**Comment by laveesingh** [comment]
I'm afraid we cannot accept props that deviate from slick libary as for now.

**Comment by gkilian** [comment]
@akiran - can we have a discussion on how we can work together to rectify these issues, instead of denying them and closing. Our end goal at Conde is to move back to this library over mantaining our fork. In doing so, we need to rectify these issues. 

From the conversations on this issue and in https://github.com/akiran/react-slick/issues/429 - it seems that this plagues more than just our organization. 

### Alternative solution
If we're going in a direction where we're not introducing props which aren't native to `slick-js` are we comfortable with defaulting the `offset` to 1? I understand this is the current functionality, however it's not working properly.

**Comment by akiran** [comment]
@gkilian We are strict about not adding new props because that will increase maintenance burden over long terms.  We are already running into issues where fix to one mode is effecting other modes. Adding more options will only make it worse. We are trying our best to fix existing issues.

We will be happy to accept PRs that fixes the issues with out adding new props at the moment. 

For this case, will it be possible to implement prefetching logic in the wrapper component of Slider.
We will be happen add such solutions to documentation

**Comment by vaibhavi3t** [comment]
@akiran I'm also using the **react-slick** and I want to load the offset amount of images. Is there any possibility of coming this feature in near future?

**Comment by sergiubologa** [comment]
Hello. Any updates on this issue? Can we at least set the default offset to 3 instead of 1?

**Comment by joshdavenport** [comment]
This would be such a great addition, any hints as to where to start on this if there isn't any existing work already ongoing on this?

**Comment by gkilian** [comment]
@sergiubologa @joshdavenport - It seems the approach we took at Conde, of adding a prop, is a no go in this repo. Let me talk to a few people tomorrow in the org and I'll try and publish a public version of our fork on my account and highlight the changes we made to get this done. 

I could submit a PR with our changes without a prop but I'd need the accepted offset amount. If that's `1` then I could also just add that.

**Comment by sergiubologa** [comment]
There's a new PR trying to solve this issue: https://github.com/akiran/react-slick/pull/1496

**Comment by joshdavenport** [comment]
@gkilian either of those actions would be worth doing imo.

In the context of this repo, surely even just lazyloading ahead by one by default when using ondemand is totally acceptable without giving the ability to change. Struggle to see that anybody would see that as a bad thing.

Definitely appears there is a hunger here for a more opinionated version of this slick component where there's scope to add nice features on top. Totally understand the difficulty though, as the comment from @akiran indicates. Perhaps it is more effort than it's worth.  🤷‍♂️
