### ISSUE TITLE
Update autoplay option, slider does not re-render :(

### ISSUE THREAD

**Issue by daiduongbian44** [akiran/react-slick#470]
Hi all, hi @akiran,
First, thanks very much for React-slick :D
Now, i'm doing with this one, and it has an issue, when Autoplay option is changed from True to False and then to True, it does not work although the props of Slider has been changed too.
I don't know what i'm doing wrong, hope you suggest for me :D
Thanks.

**Comment by TylorShin** [comment]
+1

**Comment by akiran** [comment]
Fixed this in f68bb3e68a6997aa018fa60c483be06100ec2a98

**Comment by saurishkar** [comment]
Still facing the issue.

OS : Mac OSX High Sierra
Browser: Chrome
react-slick version: 0.23.1

Issue: Setting autoplay variable from `true` -> `false` -> `true`, the carousel does not autoplay.
Checking the state params fo the inner slider component, the **`autoplaying`** param shows **paused** instead of **playing**

![image](https://user-images.githubusercontent.com/19742306/43944775-b1ffdff4-9c9d-11e8-8419-b1aee45d9bcd.png)

![image](https://user-images.githubusercontent.com/19742306/43944786-bbea5760-9c9d-11e8-81bf-be04a35d937d.png)
