### ISSUE TITLE
Empty space at the end

### ISSUE THREAD

**Issue by andricicezar** [akiran/react-slick#540]
How can I stop the carousel to let that empty space at the end?

I don't want infinite or center mode.

https://jsfiddle.net/20bumb4g/1576/

Thank you

**Comment by fahd** [comment]
i also have the same issue of the extra space at the end

**Comment by fahd** [comment]
@andricicezar did you ever get a fix for this?

**Comment by VasilyShelkov** [comment]
@fahd what parent are you suggesting to set overflow:hidden on ? I'm finding that none of the parent containers work in hiding the empty space when overflow is set to hidden :S

**Comment by mads-thines** [comment]
### I've got the same problem.
When reaching the end of the list you can scroll further like shown in the gif below.

![continuos scrolling in the end](https://cloud.githubusercontent.com/assets/16097850/25739708/584aa830-3183-11e7-80b7-781281b1bf7c.gif)

Is there anyway to solve this problem with settings or would this be considered a bug? :)

**Thanks!**

**Comment by alexjfno1** [comment]
Has anyone managed to get anything working for this? Having the same issue.

**Comment by THPubs** [comment]
@fahd To which parent should we use that? For the whole slider's parent of a single slide?

**Comment by THPubs** [comment]
Ok I solved my issue! I added a custom style to the `slick-slide` class to remove a small line on the right.

![Screenshot](http://i.imgur.com/7A2qBME.jpg)

Can you see the small light blue line on the right?
To fix it I did this:

    .slick-slide{
      margin-right: 1px;
    }

That rule caused the issue. So, in your case also there might be something which overflows the slider. I think if the inner content overflow, this happens.

**Comment by codermango** [comment]
Any update here?

**Comment by superfunkminister** [comment]
+1

**Comment by aakashlpin** [comment]
Any update here? This is kind of a show stopper.

**Comment by harshitkumar31** [comment]
+1

**Comment by calebo** [comment]
+1

**Comment by Ibrasau** [comment]
+1

**Comment by dancnnm** [comment]
+1

**Comment by Rusya13** [comment]
+1

**Comment by robertSahm** [comment]
+1

**Comment by CorwinCZ** [comment]
Bump & +1.

**Comment by vhmth** [comment]
https://www.useloom.com/share/ea64a9ea40e44344872ec6b0c75add9b

**Comment by KODerFunk** [comment]
+1

**Comment by inmutato** [comment]
+1

**Comment by djuta** [comment]
+1

**Comment by markmanx** [comment]
+1

**Comment by rafaelderolez** [comment]
+1

**Comment by freott** [comment]
+1

**Comment by laveesingh** [comment]
This has been resolved now. All you need now is to set `infinite: false`. Refer to the example: https://github.com/akiran/react-slick/blob/master/examples/UnevenSetsFinite.js

**Comment by ro0t** [comment]
infinite: false did not solve my whitespace issue..

**Comment by dryleaf** [comment]
@laveesingh @ro0t 
`infinite: false` does not solve the issue.

I also described this issue in: https://github.com/akiran/react-slick/issues/1334

**Comment by dryleaf** [comment]
@laveesingh @ro0t @mads-thines 
Did you anyone find a solution to this problem?

I also described this issue in: https://github.com/akiran/react-slick/issues/1334

**Comment by diegopamio** [comment]
I've made a fix (#1337) that would allow the finite variable width slider sliders to always fill the display area, using a new setting. I've added the pull request, not sure if it will be handled soon. In any case, you are free to use my own fork in your package.json:
"react-slick": "git+https://git@github.com/diegopamio/react-slick.git",

But ideally, if you can, also please vote so that the pull request gets attention.

**Comment by Razum** [comment]
any progress on this issue?

**Comment by dryleaf** [comment]
My ideal scroller would be the one that is:
- finite
- Variable width
- scrolls all 100% visible slides
- with no paddings or centerings

**Comment by diegopamio** [comment]
Done. I've updated the PR with those requirements.

**Comment by precompiled** [comment]
> This has been resolved now. All you need now is to set `infinite: false`. Refer to the example: https://github.com/akiran/react-slick/blob/master/examples/UnevenSetsFinite.js

This is **NOT** resolved.
Did you take into consideration variableWidth elements?

**Comment by Sidorii** [comment]
I **found solution** that works for me.
I slightly changed **Slick.prototype.getLeft** method inside the library.
So, I put additional condition at the line 1097 like shown below:
`} else if (slideIndex + _.options.slidesToShow === _.slideCount){
                //remove additional space at the end of carousel
                _.slideOffset = Math.abs($('.slick-slide').outerWidth() * _.options.slidesToShow - $(window).width());
            }`
![image](https://user-images.githubusercontent.com/20477709/47500257-fe564600-d86a-11e8-9077-b4885005d82d.png)

**Comment by Pionell** [comment]
bump  +1

**Comment by twentyoneisawesome** [comment]
bump + 1,

**Comment by baguskah** [comment]
You can add className or css in <div></div> slide wrapper with `outline: none; `

**Comment by Simonpedro** [comment]
+1

**Comment by webdevpchoi** [comment]
Hi guys, for anyone still having this issue; I fixed it by making sure that `slidesToScroll` was set to the same number as `slidesToShow`. I recognize that this isn't ideal, especially if you need to scroll slides less than the number you're showing, but in my case, it didn't matter. 

`const setting = {slidesToScroll: 6, slidesToShow: 6}`

**Comment by eyaldouwma** [comment]
if anyone still face this issue... i fixed this by setting the overflow as hidden to the Slider container

**Comment by joshianuj** [comment]
bump +1

**Comment by ramirodimodica1** [comment]
I create a PR, can you review please?
thanks.

**Comment by ramirezcgn** [comment]
This fix the issue for me, Thanks!

**Comment by groomain** [comment]
+1

**Comment by SergeyBychok** [comment]
+1

**Comment by twentyoneisawesome** [comment]
This is my solution.
in innerSliderUtils.js,
ln. 266 => targetSlide = Math.min(Math.max(0, spec.slideCount - spec.slidesToShow), currentSlide + slideOffset);
ln. 463 => newSlide = Math.min(Math.max(0, spec.slideCount - spec.slidesToShow), currentSlide + getSlideCount(spec));

**Comment by jyfernandez** [comment]
+1

**Comment by Viktor19931** [comment]
+1

**Comment by Nogias9x** [comment]
+1

**Comment by D-Flime** [comment]
+1

**Comment by n-sayenko** [comment]
+1

**Comment by n-sayenko** [comment]
I ended up removing the next buttons when the last slide was in view on the afterchange event:

```
afterChange = () => {
    const lastSlide = document.querySelector('.slick-slide:last-of-type');

    const bounding = lastSlide.getBoundingClientRect();

    if (bounding.x + 315 <= document.querySelector('.Slider__wrap').clientWidth) {
      document.querySelector('.slick-next').style.display = 'none';
    } else {
      document.querySelector('.slick-next').style.display = 'block';
    }
  };
```

**Comment by eduhdm** [comment]
I created a hack that discovers when the slider has reached the end (sum of all slides width). If it happens I change the transition to the end again and disable the button. This solution works well if your slide is controlled only by buttons (that you can disable), but it does not work well when user is changing slides by dragging:
 ```javascript
    afterChange: () => {
      const wrapperWidth = [...document.getElementsByClassName('slick-slide')]
        .map(el => el.clientWidth)
        .reduce((currWidth, acm) => acm + currWidth, 0);

      const slickContainer = document.getElementsByClassName('slick-track')[0];
      const slickList = document.getElementsByClassName('slick-list')[0];
      const minTransformWidth = -(wrapperWidth - slickList.clientWidth);

      const re = /\((-?\d*)/;
      const transformPattern = re.exec(slickContainer.style.transform);
      const transformPixels = Number(transformPattern[1]);

      slickContainer.style.width = `${wrapperWidth}px`;
      if (transformPixels < minTransformWidth) {
        setIsNextDisabled(true);
        slickContainer.style.transform = `translate3d(${minTransformWidth}px, 0px, 0px)`;
        slickContainer.style.transition = 'all 300ms ease';
      } else {
        setIsNextDisabled(false);
      }
    },
```
![captured](https://user-images.githubusercontent.com/18644659/76108342-273b2f00-5fb9-11ea-9663-11b9c2089f8d.gif)

**Comment by georgemarshall-** [comment]
+1

**Comment by Nogias9x** [comment]
+1

**Comment by kratoskat** [comment]
Hi, this is also an issue when using swipeToSlide. It seems like the issue is inside innerSlideUtils.getTrackLeft  

https://jsfiddle.net/fjLhxrqt/

**Comment by danihazler** [comment]
+1

**Comment by terreb** [comment]
bump +1

**Comment by leimonio** [comment]
+1

**Comment by Dmitri801** [comment]
+1

**Comment by LirLi** [comment]
> afterChange = () => {
>     const lastSlide = document.querySelector('.slick-slide:last-of-type');
> 
>     const bounding = lastSlide.getBoundingClientRect();
> 
>     if (bounding.x + 315 <= document.querySelector('.Slider__wrap').clientWidth) {
>       document.querySelector('.slick-next').style.display = 'none';
>     } else {
>       document.querySelector('.slick-next').style.display = 'block';
>     }
>   };

What element has class slick-next?

**Comment by amirhose1n** [comment]
finally worked , add this simple CSS code in to your project

   .slick-next{
        right:10px;
        z-index: 1000;
    }
    .slick-prev{
        left:10px;
        z-index: 1000;
    }

**Comment by parth1120** [comment]
Not able to find the exact solution, but if you keep `slidesToShow` as an even number you will not face this problem

**Comment by ko22009** [comment]
+1

**Comment by devGuerra** [comment]
+1

**Comment by Dey-Sumit** [comment]
> if anyone still face this issue... i fixed this by setting the overflow as hidden to the Slider container
Yes, it solved the issue.
```
.slick-slider {
  overflow: hidden;
}
```

**Comment by yurimutti** [comment]
+1

**Comment by araldicami** [comment]
+1

**Comment by sayinmehmet47** [comment]
our timer show 28/01/2022 but still can not find solution:)

**Comment by mthines** [comment]
The best solution for this is to switch to an alternative swiper library, like [swiper.js](https://swiperjs.com/react)

**Comment by Dmitriyx** [comment]
> 

this solved my problem

**Comment by GANESANGIDON** [comment]
> > if anyone still face this issue... i fixed this by setting the overflow as hidden to the Slider container
> > Yes, it solved the issue.
> 
> ```
> .slick-slider {
>   overflow: hidden;
> }
> ```

It worked for me thankyou.

**Comment by FerCamposDev** [comment]
with tailwind 

`<Slider className="overflow-hidden">`

works for me

**Comment by greatUzumaki** [comment]
+1
