### ISSUE TITLE
Last slide image not loading when swiping to last slide with enabled Lazyload

### ISSUE THREAD

**Issue by nelsieborja** [akiran/react-slick#628]
https://jsfiddle.net/20bumb4g/2113/

Swipe from left to right to scroll directly to the last slide, notice that image is not loading. It works fine when clicking on the prev button only when u swipe the issue is coming

**Comment by davincho** [comment]
@nelsieborja Probably you could open a PR. Would be happy if this fix get's merged soon!

**Comment by laveesingh** [comment]
All the lazyload related issues have been fixed.

**Comment by Dhruval083** [comment]
I am still getting this issue when we have multiple images on one slide, it is not working properly. below is my configuration. I am loading data from the firebase
  this.settings = {
      dots: false,
      infinite: false,
      speed: 500,
      adaptiveHeight: true,
      slidesToShow: 1,
      slidesToScroll: 1,
      useCSS: false,
      arrows: false,
      touchMove: true,
      swipeToSlide: true,
       lazyLoad: 'progressive',
      beforeChange: (oldindex, newindex) => { this.props.handleSlide(newindex) }
    };
