### ISSUE TITLE
RTL layout not working.

### ISSUE THREAD

**Issue by voodooattack** [akiran/react-slick#83]
I tried to use the right-to-left feature and it's as though the component is ignoring the prop completely.
![reac-slick rtl bug](https://dl.dropboxusercontent.com/u/27714141/react-slick-bug.png)

**Comment by vramana** [comment]
@voodooattack Are you using React compents inside the Slider?

**Comment by voodooattack** [comment]
Just this:

```
let sliderItems = [0, 1, 2, 3, 4, 5, 6 , 7, 8].map((i) =>
      <div className="image" key={i} slideIndex={i}><img width={218} height={163} src={"assets/images/" + i + ".jpg"} /></div>);
```

**Comment by vramana** [comment]
Please dont give any keys or slideIndex Slider will handle that automatically for you.

**Comment by vramana** [comment]
Can you show your the entire Slider component with settings?

**Comment by voodooattack** [comment]
```
            <Segment fluid slider>
              <Header tagName="h3" ui header>Popular Places Near You</Header>
              <Slider dots infinite speed={500} slidesToShow={4} slidesToScroll={1} centerMode adaptiveHeight rtl={rtl} >
                {sliderItems}
              </Slider>
            </Segment>
```

**Comment by vramana** [comment]
Does the Slider work with out any props properly?

**Comment by voodooattack** [comment]
Only when the html DIR attribute is set to LTR.

**Comment by vramana** [comment]
Actually Slider doesn't check for dir attribute, It just checks the for rtl prop in the slider.

**Comment by voodooattack** [comment]
I understand, but the RTL attribute apparently breaks it. I just tried specifying the "rtl" prop only and it still doesn't work.

**Comment by vramana** [comment]
Do you have react dev tools chrome extension? If not install it and can you open up the Slider component tree and send the screenshot?

**Comment by voodooattack** [comment]
![react-slick bug 2]
(https://dl.dropboxusercontent.com/u/27714141/react-slick-bug2.png)

**Comment by vramana** [comment]
Sorry, I want to see the InnerSlider tree to see the slides order.

**Comment by voodooattack** [comment]
![react-slick bug 3]
(https://dl.dropboxusercontent.com/u/27714141/react-slick-bug3.png)

**Comment by vramana** [comment]
I have checked examples in docs. `rtl` is not working with images only. It seems there is issue with Slider is applying wrong styles specifically `left` I will look into this.

**Comment by sassanh** [comment]
I'm having issues with rtl too. it only shows first slide and if I move to next slides, the div with slick-track class moves to left instead of moving to right so the div with slick-list class goes empty and nothing is visible at all (except next and previous buttons) look at this:

https://www.dropbox.com/s/lnfa5uvxyxc17oa/Screenshot%202015-11-30%2020.01.14.png?dl=0

the first argument of translate3d transition is negative, by changing return targetLeft; to return -targetLeft; in line 119 of trackHelper.js the issue is fixed in my case.

**Comment by icetronics** [comment]
Are there any updates or workarounds on this old issue? Thanks!

**Comment by icetronics** [comment]
I could not get react-slick working with rtl dir, the items are moving in the opposite direction when swiping or dragging.

**Comment by JosefJurca** [comment]
I have the same issue, any updates or workaround? Thanks:)

**Comment by jakeaaron** [comment]
I am also still seeing this issue with the newest update. The arrows appear to click and operate, but the actual slider isn't moving at all.

**Comment by iamsoorena** [comment]
you can just declare an inline style for the main container and set the direction to ltr.
it would simply solve the problem:
```
                <div className='col-xs-12' **style={{direction: "ltr"}}**>
                  <Slider {...settings}>
                    <img src='/static/images/extension-tuts/1-min.png' alt={'Screenshot 1'} />
                    <img src='/static/images/extension-tuts/2-min.png' alt={'Screenshot 2'} />
                    <img src='/static/images/extension-tuts/3-min.png' alt={'Screenshot 3'} />
                    <img src='/static/images/extension-tuts/4-min.png' alt={'Screenshot 4'} />
                    <img src='/static/images/extension-tuts/5-min.png' alt={'Screenshot 5'} />
                  </Slider>
                </div>
```

**Comment by FarzadKarkhani** [comment]
I have same problem with RTL props,
I tried to set RTL props and its only reverse order of  slides, Its happen even in your demo page.
I found out original Slick Slider demo is OK for rtl but this library for react has some issue for RTL support.

**Comment by akiran** [comment]
This is fixed in the latest release

**Comment by sag1v** [comment]
@quarklemotion  Actually it is not fixed on react-slick@0.16.0.
As other have mentioned here and in #926 and #880 and #839 .
It seems that the `tranform: translate3d` and `width` calculations are off. so when `rtl` is `true`, you can't see the slides.

**Comment by sag1v** [comment]
@akiran I'm not sure but i think [this is the place](https://github.com/akiran/react-slick/blob/master/src/mixins/trackHelper.js#L35) that need to be changed, or at least the starter point, there is no condition for `rtl` here, only for `vertical`.

**Comment by sag1v** [comment]
After playing with the source code a bit (in `src/mixins/trackHelper`),
I think the solution or at least part of it, is to change [this block code](https://github.com/akiran/react-slick/blob/master/src/mixins/trackHelper.js#L20):
```
 if (!spec.vertical) {
    if (spec.variableWidth) {
      trackWidth = (spec.slideCount + 2*spec.slidesToShow) * spec.slideWidth;
    } else if (spec.centerMode) {
      trackWidth = (spec.slideCount + 2*(spec.slidesToShow + 1)) * spec.slideWidth;
    } else {
      trackWidth = (spec.slideCount + 2*spec.slidesToShow) * spec.slideWidth;
    }
  } else {
    trackHeight = trackChildren * spec.slideHeight;
  }
```

To this:
```
  if (!spec.vertical) {
	if(spec.rtl){ // added condition for rtl
		trackWidth = 0;
	} else if (spec.variableWidth) {
      trackWidth = (spec.slideCount + 2 * spec.slidesToShow) * spec.slideWidth;
    } else if (spec.centerMode) {
      trackWidth = (spec.slideCount + 2 * (spec.slidesToShow + 1)) * spec.slideWidth;
    } else {
      trackWidth = (spec.slideCount + 2 * spec.slidesToShow) * spec.slideWidth;
    }
  } else {
    trackHeight = trackChildren * spec.slideHeight;
  }
```
and[ this block code](https://github.com/akiran/react-slick/blob/master/src/mixins/trackHelper.js#L32):
```
  var style = {
    opacity: 1,
    WebkitTransform: !spec.vertical ? 'translate3d(' + spec.left + 'px, 0px, 0px)' : 'translate3d(0px, ' + spec.left + 'px, 0px)',
    transform: !spec.vertical ? 'translate3d(' + spec.left + 'px, 0px, 0px)' : 'translate3d(0px, ' + spec.left + 'px, 0px)',
    transition: '',
    WebkitTransition: '',
    msTransform: !spec.vertical ? 'translateX(' + spec.left + 'px)' : 'translateY(' + spec.left + 'px)',
  };
```
to this:
```
  var style = {
    opacity: 1,
    WebkitTransform: !spec.vertical ? 'translate3d(' + (spec.rtl? 0 : spec.left) + 'px, 0px, 0px)' : 'translate3d(0px, ' + spec.left + 'px, 0px)',
    transform: !spec.vertical ? 'translate3d(' + (spec.rtl? 0 : spec.left) + 'px, 0px, 0px)' : 'translate3d(0px, ' + spec.left + 'px, 0px)',
    transition: '',
    WebkitTransition: '',
    msTransform: !spec.vertical ? 'translateX(' + (spec.rtl? 0 : spec.left) + 'px)' : 'translateY(' + spec.left + 'px)'
  };
```

It would be nice if other can confirm that this solution works well.
