### ISSUE TITLE
variableWidth + centerMode

### ISSUE THREAD

**Issue by ChrisAllinson** [akiran/react-slick#832]
I'm using the "variableWidth" prop and am finding that slides do not perfectly center when using `centerMode + variableWidth` ... they appear a bit too far offset right.

Here's an example:
[jsfiddle](https://jsfiddle.net/20bumb4g/4142/)

I'd like the active slide's center to align with the center of the scroller. It doesn't seem to take into account the variable widths in it's calculation.

<img width="593" alt="not centered" src="https://user-images.githubusercontent.com/8192008/29582285-1eb33f98-874a-11e7-8051-faa968636af0.png">

**Comment by antiwebbite** [comment]
I was also having this problem. Setting centerPadding to 0 seemed to fix the alignment for me. I noticed it was offset by 50px and low and behold, the default centerPadding is 50px.

I also just did this, know very little about coding, so I don't know if that causes issues elsewhere or isn't a solution for others, but thought I'd share.

**Comment by laveesingh** [comment]
This has been fixed. Please make sure you are using the latest version of react-slick.

**Comment by alimtunc** [comment]
This is not fixed, getting same issue with the latest version.
