### ISSUE TITLE
initialSlide doesn't work properly in case of variableWidth and infinite:true

### ISSUE THREAD

**Issue by laveesingh** [akiran/react-slick#965]
Initial slide is shown as `initialSlide-1` in case of `variableWidth` and `inifite = true`

**Comment by Wgil** [comment]
How did you test this? 

These are my settings:
```
var settings = {
      dots         : true,
      infinite     : true,
      initialSlide : 1,
      variableWidth: true,
    };
```
Inspecting in the React Developer Tools, I see the ```currentSlide``` state of ```Track``` equals to ```initialSlide``` initial prop

**Comment by march08** [comment]
I have the same problem. 
The thing is that slick does some calculation but doesn't rerender afterwards.

In my case:
On initial render, the second item is visible (probably n - 2), when i click back, it magically slides to the last (n-1) so in the calculations on init, 0 is set as initial but not rendered.

Hotfix solution, it's stupid, but it works:

`` javascript
class ExtendedCarousel extends React.Component { 
  componentDidMount() {
    // the trick
    setTimeout(() => {
      this.forceUpdate();
    }, 50);
  }

  render() {
    const settings = {
      lazyRender: true,
      infinite: true,
      slidesToShow: 1,
      slidesToScroll: 1,
      centerMode: true,
      variableWidth: true,
    };
    return (
      <Slider {...settings}>
        <div>
            <h3>1</h3>
        </div>
        <div>
            <h3>2</h3>
        </div>
        <div>
            <h3>3</h3>
        </div>
      </Slider>
    );
  }

}
``

As you can see, I am forcing rerender. It causes a 50ms glitch (or your timeout) so some fade in animation with delay is necessary.

**Comment by probedb** [comment]
This solves an unrelated problem I seem to have which I've had with React components before. It needs a 50ms delay for the browser to sort itself out and React to get updates. This was required with some scrolling that was supposed to happen on page load for me in a separate issue.

**Comment by march08** [comment]
Actually I don't think this is a react problem more like the react shouldComponentUpdate didn't detect any change. I assume that there are some problems with passing props in the library or some mutation is happening (which shouldn't) so the slick component doesn't return true on shouldComponentUpdate, thus no re rendering happens.

**Comment by laveesingh** [comment]
fixed.
probably in: 071a29cea6e1b99f66cc49c20ed2c2e6131e3bb9

**Comment by FootyNumb3rs** [comment]
This hasn't been properly fixed for me. I'm still getting the issue when variableWidth: true
