### ISSUE TITLE
getDotCount doesn't take slidesToShow into account

### ISSUE THREAD

**Issue by scolacur** [akiran/react-slick#989]
If I have 13 items, slidesToShow = 10 and slidesToScroll = 3, I would expect 2 dots. But the current calculation yields 5 dots, because it doesn't take slidesToShow into account.

I think a better calculation would be:
`Math.ceil((spec.slideCount - spec.slidesToShow) / spec.slidesToScroll) + 1`

**Comment by scolacur** [comment]
update: i just saw that there is already a fix for this in PR

https://github.com/akiran/react-slick/pull/766/files

**Comment by ste93cry** [comment]
Same here, I have a slider with 5 items, `slidesToShow` set to 5 and `slidesToScroll` set to 1 and the dots are 5. I expect to see only one dot instead

**Comment by laveesingh** [comment]
This has been fixed by #766 and 1-2 additional commits that I made into dev branch. This would be merged to master soon enough.

**Comment by ste93cry** [comment]
I upgraded to 0.18.0 and still have the problem. I think that version includes the fix you mentioned. Configuration is still the same written in my previous comment
